import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — CareerCompass",
  description:
    "Terms of using CareerCompass — what's allowed, what's not, and the limits of our advice.",
};

const LAST_UPDATED = "April 2026";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 sm:py-16">
      <Link
        href="/"
        className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-neutral-600 hover:text-neutral-900"
      >
        <span>←</span>
        <span>Back to home</span>
      </Link>

      <header className="mb-10">
        <span className="eyebrow">Terms</span>
        <h1 className="mt-2 text-3xl font-extrabold tracking-tight text-neutral-900 sm:text-4xl">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-neutral-500">Last updated: {LAST_UPDATED}</p>
      </header>

      <div className="space-y-8 text-[15px] leading-relaxed text-neutral-800">
        <section className="rounded-2xl bg-amber-50 p-5 ring-1 ring-amber-200/70">
          <h2 className="m-0 text-lg font-bold text-amber-900">TL;DR</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5 text-amber-900/90">
            <li>CareerCompass is a free-to-try AI tool with daily usage quotas. It&apos;s not a recruiter, employer, or career counsellor.</li>
            <li>AI output can be wrong. Use your own judgement before applying for anything.</li>
            <li>Don&apos;t abuse the service (bulk scraping, automated requests, etc.).</li>
            <li>Provided as-is, no warranty. We&apos;re not liable for outcomes from using the advice.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-900">1. The service</h2>
          <p className="mt-2">
            CareerCompass (&ldquo;the Service&rdquo;) is an AI-powered career toolkit operated as an open-source project. Use of the AI tools requires sign-in and is currently offered with a daily free quota of 5 runs per signed-in user, shared across all tools; paid plans for higher usage may be introduced in the future.
            It uses <strong>Google Gemini</strong> to analyse CVs and generate suggestions across four tools:
            Career Map, Resume Studio, JD Ghost Buster, and Career Journey.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-900">2. Acceptance</h2>
          <p className="mt-2">
            By using the Service, you agree to these Terms and our <Link href="/privacy" className="font-semibold text-indigo-700 underline">Privacy Policy</Link>.
            If you don&apos;t agree, don&apos;t use it.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-900">3. AI output is not advice</h2>
          <p className="mt-2">
            The Service&apos;s output is generated by an AI model and can be incorrect, outdated, or misleading.
            It is <strong>not</strong>:
          </p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Professional career counselling.</li>
            <li>A guarantee of getting an interview, offer, or specific salary.</li>
            <li>Legal, financial, or medical advice.</li>
          </ul>
          <p className="mt-2">
            Verify everything before acting on it. Job markets, salaries, and ATS behaviour change.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-900">4. Acceptable use</h2>
          <p className="mt-2">You agree <strong>not</strong> to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Submit content that isn&apos;t yours, or that you don&apos;t have permission to share.</li>
            <li>Submit illegal, defamatory, or discriminatory content.</li>
            <li>Run automated requests, scrape the Service, or attempt to overload it.</li>
            <li>Reverse-engineer or attempt to extract our prompts or model behaviour.</li>
            <li>Use the Service to generate content that violates any third party&apos;s rights.</li>
          </ul>
          <p className="mt-2">
            We may rate-limit or block IPs / accounts that abuse the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-900">5. Your content</h2>
          <p className="mt-2">
            You keep all rights to the CV and inputs you submit. By submitting them, you give us a limited licence
            to send them to Google Gemini for processing and to display the resulting analysis back to you.
            We do not use your content to train models.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-900">6. Accounts</h2>
          <p className="mt-2">
            Accounts are optional. If you create one, you&apos;re responsible for keeping your sign-in credentials secure.
            We can suspend accounts for abuse without prior notice.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-900">7. No warranty</h2>
          <p className="mt-2">
            The Service is provided <strong>&ldquo;as is&rdquo; and &ldquo;as available&rdquo;</strong>, without warranty of any kind,
            express or implied — including merchantability, fitness for a particular purpose, or non-infringement.
            We don&apos;t promise the Service will be uninterrupted, error-free, or always available.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-900">8. Limitation of liability</h2>
          <p className="mt-2">
            To the fullest extent permitted by law, CareerCompass and its maintainers are <strong>not liable</strong> for
            any indirect, incidental, consequential, or special damages — including missed jobs, lost income, or
            decisions made based on the AI&apos;s output. Total aggregate liability for any claim is capped at <strong>USD $0</strong>,
            reflecting the fact that the Service is provided free of charge.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-900">9. Third-party services</h2>
          <p className="mt-2">
            We rely on Google Gemini, Supabase, and Vercel. Their terms apply to their portion of the Service.
            We&apos;re not responsible for their availability or actions.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-900">10. Changes</h2>
          <p className="mt-2">
            We may update these Terms. Material changes will be reflected in the &ldquo;Last updated&rdquo; date.
            Continued use after a change means you accept it.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-neutral-900">11. Contact</h2>
          <p className="mt-2">
            Questions, abuse reports, or DMCA: open an issue at{" "}
            <a href="https://github.com/siddhu-tri2000/career-compass/issues" target="_blank" rel="noreferrer" className="font-semibold text-indigo-700 underline">github.com/siddhu-tri2000/career-compass</a>.
          </p>
        </section>
      </div>

      <div className="mt-12 flex flex-wrap items-center justify-between gap-3 border-t border-neutral-200 pt-6 text-sm text-neutral-500">
        <Link href="/privacy" className="hover:text-neutral-800">Privacy Policy →</Link>
        <Link href="/" className="hover:text-neutral-800">← Back to home</Link>
      </div>
    </main>
  );
}
